# 08-6. 예외 발생시키기
키워드 throw를 사용해서 프로그래머가 고의로 예외를 발생시킬 수 있으며, 방법은 아래의 순서를 따르면 된다.
1. 먼저, 연산자 new를 이용해서 발생시키려는 예외 클래스의 객체를 만든 다음
```java
Exception e = new Exception("고의로 발생시켰음");
```
2. 키워드 throw를 이용해서 예외를 발생시킨다.
```java
throw e;
```
```java
package ch08;

public class ExceptionEx9 {

	public static void main(String[] args) {
		try {
			Exception e = new Exception("고의로 발생시켰음.");
			throw e;
			//throw new Exception("고의로 발생시켰음.");
		} catch(Exception e) {
			System.out.println("에러 메시지: " + e.getMessage());
			e.printStackTrace();
		}
		System.out.println("프로그램이 정상 종료되었음.");
	}

}
```
```
에러 메시지: 고의로 발생시켰음.
java.lang.Exception: 고의로 발생시켰음.
	at book2/ch08.ExceptionEx9.main(ExceptionEx9.java:7)
프로그램이 정상 종료되었음.
```
Exception인스턴스를 생성할 때, 생성자에 String을 넣어 주면, 이 String이 Exception 인스턴스에 메시지로 저장된다. 
이 메시지는 getMessage()를 이용해서 얻을 수 있다.

'Exception클래스들(Exception클래스와 그 자손들)'이 발생할 가능성이 있는 문장들에 대해 예외처리를 해주지 않으면 컴파일조차 되지 않으니,
예외처리를 반드시 해주어야 한다.

그러나, RuntimeException은 발생시키고 예외처리를 하지 않아도 성공적으로 컴파일될 것이다. 실행하면 비정상적으로 종료될 것이지만 말이다.
'RuntimeException클래스와 그 자손(RuntimeException클래스들)'에 해당하는 예외는 프로그래머에 의해 실수로 발생하는 것들이기 때문에 예외처리를 강제하지 않는 것이다.

컴파일러가 예외처리를 확인하지 않는 RuntimeException클래스들은 'unchecked예외'라고 부르고, 
예외처리를 확인하는 Exception클래스들은 'checked예외'라고 부른다.
